name: Deploy API ti Azure App Service
on:
  push:
    branches: [AzureAppService]
env:
  AZURE_WEBAPP_NAME: simpletodoapi87623
  AZURE_WEBAPP_PACKAGE_PATH: '.'
jobs:
  deploy-to-appservice:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build web app
        uses: azure/appservice-build@v2
      - name: Deploy web app
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
